version: '3.8'

services:
  resumencolombiatours:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    networks:
      - webnet

networks:
  webnet:
    external: true



